package com.example.hhplusweek3.domain.model.exception

enum class ErrorCode(
    val code: String,
    val message: String = "",
) {
    QUEUE_NOT_FOUND("QUEUE_NOT_FOUND"),
    RESERVATION_NOT_FOUND("RESERVATION_NOT_FOUND"),
    WALLET_NOT_FOUND("WALLET_NOT_FOUND"),
    CONCERT_DATE_NOT_FOUND("CONCERT_DATE_NOT_FOUND"),
    CONCERT_SEAT_NOT_FOUND("CONCERT_SEAT_NOT_FOUND"),
    INVALID_QUEUE_STATUS("INVALID_QUEUE_STATUS"),
    QUEUE_LIMIT_EXCEEDED("QUEUE_LIMIT_EXCEEDED"),
    INVALID_RESERVATION("INVALID_RESERVATION"),
    INSUFFICIENT_BALANCE("INSUFFICIENT_BALANCE"),
    ALREADY_PAID_RESERVATION("ALREADY_PAID_RESERVATION"),
    ACQUIRE_LOCK_FAILED("ACQUIRE_LOCK_FAILED"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
}
