version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword    # Root password
      MYSQL_DATABASE: mydb                 # Database to create on startup
      MYSQL_USER: user                     # Create a user
      MYSQL_PASSWORD: userpassword         # User password
    ports:
      - "3306:3306"                       # Host:Container port mapping
    volumes:
      - mysql_data:/var/lib/mysql         # Persist data even if container is removed
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Optional: initialize with custom SQL
    command:
      - --default-authentication-plugin=mysql_native_password  # For compatibility
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:                             # Named volume for data persistence