name: Update API Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-api-docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install swagger-markdown
        run: npm install -g swagger-markdown
      
      - name: Update API documentation
        run: |
          ./gradlew bootRun &
          sleep 30
          curl http://localhost:8080/v3/api-docs -o openapi.json
          pkill -f "java -jar"
          npx swagger-markdown -i openapi.json -o "docs/API 명세.md"
          rm openapi.json
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "docs/API 명세.md"
          git commit -m "Update API documentation in docs/API 명세.md" || echo "No changes to commit"
          git push